//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18010
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquilaWeb.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aquila.com/ServiceHandler", ConfigurationName="ServiceReference1.SettingsHandler")]
    public interface SettingsHandler {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aquila.com/ServiceHandler/SettingsHandler/SetSetting", ReplyAction="http://aquila.com/ServiceHandler/SettingsHandler/SetSettingResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        bool SetSetting(object[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aquila.com/ServiceHandler/SettingsHandler/PerformAction", ReplyAction="http://aquila.com/ServiceHandler/SettingsHandler/PerformActionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        bool PerformAction(object[] args);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SettingsHandlerChannel : AquilaWeb.ServiceReference1.SettingsHandler, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SettingsHandlerClient : System.ServiceModel.ClientBase<AquilaWeb.ServiceReference1.SettingsHandler>, AquilaWeb.ServiceReference1.SettingsHandler {
        
        public SettingsHandlerClient() {
        }
        
        public SettingsHandlerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SettingsHandlerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SettingsHandlerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SettingsHandlerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SetSetting(object[] args) {
            return base.Channel.SetSetting(args);
        }
        
        public bool PerformAction(object[] args) {
            return base.Channel.PerformAction(args);
        }
    }
}
